on:
  workflow_call:
    inputs:
      version:
        default: ${GITHUB_REF#refs/tags/}
        type: string
      service:
        type: string
        required: true
      context:
        type: string
        default: .
    secrets:
      GIT_AUTH_TOKEN:
        required: false
        description: The github PAT to use in order to fetch from private registries
    outputs:
      tag:
        description: The generated and pushed image tag
        value: ${{ jobs.build_and_push.outputs.tag }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.prepare_tag.outputs.tag }}
    steps:
  
    - name: Prepare image tags
      id: prepare_tag
      run: echo ::set-output name=tag::europe-west3-docker.pkg.dev/ams-pro-2022/ams-pro/${{ inputs.service }}:${{ inputs.version }}

    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0'
      with:
          workload_identity_provider: 'projects/205623571289/locations/global/workloadIdentityPools/ams-pro/providers/github-actions'
          service_account: ' github-actions-test@ams-pro-2022.iam.gserviceaccount.com'
          token_format: 'access_token'

    - uses: docker/setup-buildx-action@v2
      name: Set up Docker Buildx

    - uses: 'docker/login-action@v1'
      with:
        registry: 'europe-west3-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
  
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ steps.prepare_tag.outputs.tag }}
        build-args: |
          GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN || "" }}

      
